version: '3.8'
services:
  mysql:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_ROOT_API}
      MYSQL_DATABASE: ${MYSQL_DATABASE_API}
      MYSQL_USER: ${MYSQL_USER_API}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_API}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3307:3306'
