version: '3.8'
services:
  mysql:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD_ROOT_DOCKER}
      MYSQL_DATABASE: ${DATABASE_DATABASE_API}
      MYSQL_USER: ${DATABASE_USER_API}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD_API}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3309:3309'
